name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Create .env file
        run: |
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env
          echo "VITE_FREEINDEX_API_BASE_URL=${{ secrets.VITE_FREEINDEX_API_BASE_URL }}" >> .env

      - name: Install dependencies and build
        run: |
          npm ci
          npx nuxi generate

      - name: Deploy to Firebase
        run: |
          npx firebase-tools deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project set2pass-e6e33 --json
